/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#fee2e2',
        'surface-container-low': '#f1f5f9',
        'surface-container': '#e8edf3',
        surface: '#f8fafc',
        'on-tertiary': '#ffffff',
        'surface-dim': '#e2e8f0',
        'on-primary-fixed-variant': '#475569',
        'surface-container-high': '#e2e8f0',
        'tertiary-container': '#7f1d1d',
        'on-tertiary-fixed': '#450a0a',
        'on-primary-fixed': '#0f172a',
        'on-primary': '#ffffff',
        'on-background': '#0f172a',
        'secondary-fixed': '#dbeafe',
        'inverse-on-surface': '#f1f5f9',
        'surface-tint': '#64748b',
        'inverse-surface': '#1e293b',
        'on-secondary-fixed': '#1e3a8a',
        secondary: '#2563eb',
        'on-secondary-container': '#1d4ed8',
        'tertiary-fixed-dim': '#fca5a5',
        'on-primary-container': '#94a3b8',
        'secondary-container': '#bfdbfe',
        'inverse-primary': '#93c5fd',
        'secondary-fixed-dim': '#93c5fd',
        'surface-bright': '#f8fafc',
        'on-surface': '#0f172a',
        'surface-variant': '#e2e8f0',
        'on-tertiary-container': '#f87171',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#b91c1c',
        outline: '#94a3b8',
        'primary-fixed': '#dbeafe',
        'tertiary-fixed': '#fecaca',
        'primary-fixed-dim': '#93c5fd',
        'on-error-container': '#7f1d1d',
        'surface-container-highest': '#cbd5e1',
        'primary-container': '#0f172a',
        tertiary: '#450a0a',
        'on-secondary-fixed-variant': '#1e40af',
        'on-surface-variant': '#64748b',
        error: '#dc2626',
        primary: '#0f172a',
        background: '#f8fafc',
        'outline-variant': '#e2e8f0',
        'on-error': '#ffffff',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        'gutter-sm': '0.75rem',
        margin: '2.5rem',
        gutter: '1.5rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        sans: ['Public Sans', 'system-ui', 'sans-serif'],
        'body-lg': ['Public Sans', 'system-ui', 'sans-serif'],
        'label-caps': ['IBM Plex Mono', 'monospace'],
        'headline-lg-mobile': ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'headline-xl': ['Sora', 'sans-serif'],
        'data-mono-lg': ['IBM Plex Mono', 'monospace'],
        'headline-md': ['Sora', 'sans-serif'],
        'headline-xl-mobile': ['Sora', 'sans-serif'],
        'data-mono-md': ['IBM Plex Mono', 'monospace'],
        'body-md': ['Public Sans', 'system-ui', 'sans-serif'],
        'body-sm': ['Public Sans', 'system-ui', 'sans-serif'],
        'editorial-subhead': ['Public Sans', 'system-ui', 'sans-serif'],
        'data-mono-sm': ['IBM Plex Mono', 'monospace'],
      },
      fontSize: {
        'body-lg': ['17px', { lineHeight: '26px', fontWeight: '400' }],
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.12em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['38px', { lineHeight: '44px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-xl': ['56px', { lineHeight: '60px', letterSpacing: '0.02em', fontWeight: '700' }],
        'data-mono-lg': ['16px', { lineHeight: '22px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['26px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['36px', { lineHeight: '40px', letterSpacing: '0.02em', fontWeight: '700' }],
        'data-mono-md': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'editorial-subhead': ['18px', { lineHeight: '27px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'data-mono-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '400' }],
      },
      boxShadow: {
        card: '0 1px 2px 0 rgb(15 23 42 / 0.05), 0 1px 3px 0 rgb(15 23 42 / 0.08)',
        pop: '0 8px 24px -8px rgb(15 23 42 / 0.18)',
      },
      borderRadius: {
        xl: '0.875rem',
        '2xl': '1.125rem',
      },
    },
  },
  plugins: [],
};
