/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'surface-container-low': '#f7f3ed',
        'surface-container': '#f1ede7',
        surface: '#fdf9f3',
        'on-tertiary': '#ffffff',
        'surface-dim': '#ddd9d4',
        'on-primary-fixed-variant': '#3c475d',
        'surface-container-high': '#ebe8e2',
        'tertiary-container': '#540211',
        'on-tertiary-fixed': '#40000a',
        'on-primary-fixed': '#101b30',
        'on-primary': '#ffffff',
        'on-background': '#1c1c18',
        'secondary-fixed': '#d3e3ff',
        'inverse-on-surface': '#f4f0ea',
        'surface-tint': '#545e76',
        'inverse-surface': '#31302d',
        'on-secondary-fixed': '#001c39',
        secondary: '#436086',
        'on-secondary-container': '#3c597f',
        'tertiary-fixed-dim': '#ffb3b4',
        'on-primary-container': '#828da7',
        'secondary-container': '#b3d1fd',
        'inverse-primary': '#bbc6e2',
        'secondary-fixed-dim': '#abc8f4',
        'surface-bright': '#fdf9f3',
        'on-surface': '#1c1c18',
        'surface-variant': '#e6e2dc',
        'on-tertiary-container': '#dc6a6f',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#81252e',
        outline: '#75777d',
        'primary-fixed': '#d7e2ff',
        'tertiary-fixed': '#ffdad9',
        'primary-fixed-dim': '#bbc6e2',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e6e2dc',
        'primary-container': '#1b263b',
        tertiary: '#2d0005',
        'on-secondary-fixed-variant': '#2a486d',
        'on-surface-variant': '#45474d',
        error: '#ba1a1a',
        primary: '#051125',
        background: '#fdf9f3',
        'outline-variant': '#c5c6cd',
        'on-error': '#ffffff',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        'gutter-sm': '0.75rem',
        margin: '2.5rem',
        gutter: '1.5rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        'body-lg': ['Newsreader', 'serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-lg-mobile': ['Oswald', 'sans-serif'],
        'headline-lg': ['Oswald', 'sans-serif'],
        'headline-xl': ['Oswald', 'sans-serif'],
        'data-mono-lg': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Oswald', 'sans-serif'],
        'headline-xl-mobile': ['Oswald', 'sans-serif'],
        'data-mono-md': ['JetBrains Mono', 'monospace'],
        'body-md': ['Newsreader', 'serif'],
        'body-sm': ['Newsreader', 'serif'],
        'editorial-subhead': ['Newsreader', 'serif'],
        'data-mono-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-lg': ['17px', { lineHeight: '26px', fontWeight: '400' }],
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.12em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['38px', { lineHeight: '44px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-xl': ['56px', { lineHeight: '60px', letterSpacing: '0.02em', fontWeight: '700' }],
        'data-mono-lg': ['16px', { lineHeight: '22px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['26px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['36px', { lineHeight: '40px', letterSpacing: '0.02em', fontWeight: '700' }],
        'data-mono-md': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'editorial-subhead': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'data-mono-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
